//
//  NearbyCryptoTests.swift
//  BuddyDataTests
//
//  Created by Soongyu Kwon on 04/10/2026.
//

import Foundation
import CryptoKit
import Testing
@testable import BuddyDataCore

/// Reproduces `nearby-test-vectors.json`, shared with Android and generated by
/// the backend's reference implementation. Both apps must match every value.
@Suite("Nearby crypto test vectors")
struct NearbyCryptoTests {
  struct Vectors: Decodable {
    struct Party: Decodable {
      let privateKeyRaw, publicKeyX963, token, beaconUuid, lookupId, presenceKey: String
      let ownerSecret, ownerSecretBase64Url: String
    }
    struct Sealed: Decodable {
      let plaintextUtf8: String?
      let plaintext: String?
      let key: String?
      let aad, nonce, sealed: String
      let sealedBase64Url: String?
    }
    struct Pair: Decodable {
      let sharedSecret, salt, pairKey: String
    }
    let version: Int
    let a, b: Party
    let presence, header, body: Sealed
    let pair: Pair
    let beacon: [String: [String]]
  }

  let vectors: Vectors

  init() throws {
    let url = try #require(Bundle.module.url(forResource: "nearby-test-vectors", withExtension: "json"))
    vectors = try JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
  }

  private func hex(_ string: String) -> Data {
    Data(hexString: string)!
  }

  private func session(_ party: Vectors.Party) throws -> NearbySession {
    NearbySession(
      privateKey: try P256.KeyAgreement.PrivateKey(rawRepresentation: hex(party.privateKeyRaw)),
      ownerSecret: hex(party.ownerSecret)
    )
  }

  @Test(arguments: ["a", "b"])
  func derivesSessionValues(name: String) throws {
    let party = name == "a" ? vectors.a : vectors.b
    let session = try session(party)
    #expect(session.publicKeyX963.hexString == party.publicKeyX963)
    #expect(session.token.hexString == party.token)
    #expect(session.lookupId.hexString == party.lookupId)
    #expect(session.presenceKey.data.hexString == party.presenceKey)
    #expect(session.ownerSecret.base64URLEncodedString() == party.ownerSecretBase64Url)
    #expect(NearbyBeaconUUID.string(for: session.token) == party.beaconUuid)
  }

  @Test func sealsPresenceCard() throws {
    let a = try session(vectors.a)
    let presence = vectors.presence
    #expect(NearbyCrypto.presenceAAD(lookupId: a.lookupId).hexString == presence.aad)
    // The card's JSON is sealed exactly as given so the bytes are comparable.
    let sealed = try NearbyCrypto.seal(
      Data(presence.plaintextUtf8!.utf8),
      key: a.presenceKey,
      aad: hex(presence.aad),
      nonce: try AES.GCM.Nonce(data: hex(presence.nonce))
    )
    #expect(sealed.hexString == presence.sealed)
    #expect(sealed.base64URLEncodedString() == presence.sealedBase64Url)
  }

  @Test func opensAndVerifiesPresence() throws {
    let (card, publicKey) = try NearbyCrypto.openPresence(hex(vectors.presence.sealed), token: hex(vectors.a.token))
    #expect(card.name == "홍길동")
    #expect(card.platform == "ios")
    #expect(publicKey.x963Representation.hexString == vectors.a.publicKeyX963)
  }

  @Test func sealsHeader() throws {
    let a = try session(vectors.a)
    let b = try session(vectors.b)
    let header = vectors.header
    #expect(NearbyCrypto.headerAAD(recipientLookupId: b.lookupId).hexString == header.aad)
    let sealed = try NearbyCrypto.seal(
      a.token,
      key: NearbyCrypto.presenceKey(for: b.token),
      aad: hex(header.aad),
      nonce: try AES.GCM.Nonce(data: hex(header.nonce))
    )
    #expect(sealed.hexString == header.sealed)
    let opened = try NearbyCrypto.open(sealed, key: b.presenceKey, aad: hex(header.aad))
    #expect(opened.hexString == header.plaintext)
  }

  @Test func derivesSamePairKeyOnBothSides() throws {
    let a = try session(vectors.a)
    let b = try session(vectors.b)
    let shared = try a.privateKey.sharedSecretFromKeyAgreement(with: b.privateKey.publicKey)
    #expect(shared.withUnsafeBytes { Data($0) }.hexString == vectors.pair.sharedSecret)

    let fromA = try NearbyCrypto.pairKey(privateKey: a.privateKey, peerPublicKey: b.privateKey.publicKey, myToken: a.token, peerToken: b.token)
    let fromB = try NearbyCrypto.pairKey(privateKey: b.privateKey, peerPublicKey: a.privateKey.publicKey, myToken: b.token, peerToken: a.token)
    #expect(fromA.data.hexString == vectors.pair.pairKey)
    #expect(fromB.data.hexString == vectors.pair.pairKey)
  }

  @Test func sealsBody() throws {
    let a = try session(vectors.a)
    let b = try session(vectors.b)
    let body = vectors.body
    #expect(NearbyCrypto.bodyAAD(recipientLookupId: b.lookupId, senderToken: a.token).hexString == body.aad)
    let key = SymmetricKey(data: hex(vectors.pair.pairKey))
    let sealed = try NearbyCrypto.seal(
      Data(body.plaintextUtf8!.utf8),
      key: key,
      aad: hex(body.aad),
      nonce: try AES.GCM.Nonce(data: hex(body.nonce))
    )
    #expect(sealed.hexString == body.sealed)

    let decoded = try JSONDecoder().decode(NearbyMessageBody.self, from: NearbyCrypto.open(sealed, key: key, aad: hex(body.aad)))
    #expect(decoded.messageType == .accept)
    #expect(decoded.friendCode == "ACD347")
    #expect(decoded.sentAt == 1790590000123)
  }

  // MARK: - Rejections

  @Test func tamperedCiphertextFails() throws {
    var sealed = hex(vectors.body.sealed)
    sealed[sealed.count - 1] ^= 0x01
    #expect(throws: (any Error).self) {
      try NearbyCrypto.open(sealed, key: SymmetricKey(data: hex(vectors.pair.pairKey)), aad: hex(vectors.body.aad))
    }
  }

  @Test func wrongAADFails() throws {
    #expect(throws: (any Error).self) {
      // Same ciphertext, but claimed to be for B's mailbox instead of A's.
      try NearbyCrypto.open(
        hex(vectors.presence.sealed),
        key: SymmetricKey(data: hex(vectors.a.presenceKey)),
        aad: NearbyCrypto.presenceAAD(lookupId: hex(vectors.b.lookupId))
      )
    }
  }

  /// A relay that swaps in its own key must re-encrypt the card under the
  /// presence key, which anyone with the token can do — so only the
  /// commitment check stands between it and a man in the middle.
  @Test func substitutedKeyIsRejected() throws {
    let a = try session(vectors.a)
    let attacker = NearbySession()
    let forged = NearbyPresenceCard(pub: attacker.publicKeyX963.base64URLEncodedString(), name: "홍길동")
    let blob = try NearbyCrypto.sealPresence(forged, session: a)
    #expect(throws: NearbyCryptoError.commitmentMismatch) {
      try NearbyCrypto.openPresence(blob, token: a.token)
    }
  }

  @Test func randomSessionsRoundTrip() throws {
    let session = NearbySession()
    let card = NearbyPresenceCard(pub: session.publicKeyX963.base64URLEncodedString(), name: "Minho")
    let opened = try NearbyCrypto.openPresence(NearbyCrypto.sealPresence(card, session: session), token: session.token)
    #expect(opened.card == card)
    #expect(session.ownerSecret.count == 32)
    #expect(session.ownerSecret != NearbySession().ownerSecret)
  }

  @Test func truncatesLongNames() {
    let name = String(repeating: "가", count: 30) // 90 UTF-8 bytes
    let truncated = NearbyPresenceCard.truncatedName(name)
    #expect(truncated.utf8.count == 63)
    #expect(NearbyPresenceCard.truncatedName("  Minho Lee ") == "Minho Lee")
  }
}
